version: "3.9"

services:
  postgres:
    image: postgres:14.2-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  redis:
    image: redis:6.2.6-alpine
    volumes:
      - redis:/var/lib/redis/data

  nginx:
    image: nginx:1.21-alpine
    volumes:
      - .:/app
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: sh -c "bundle exec unicorn -E production -c config/unicorn.rb"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis

volumes:
  postgres:
  redis:
